---
# Connection settings
ansible_connection: community.aws.aws_ssm
ansible_aws_ssm_region: ap-southeast-1
# Replace with your actual bucket name to prevent NoneType discovery errors
ansible_aws_ssm_bucket_name: "ansible-ssm-transfer-686255953032-ap-southeast-1"

ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3

# Environment & Temp Directories
TF_STATE_BUCKET: "terraform-state-devops-bootcamp-faizpuad"
remote_tmp: /tmp/.ansible/tmp
local_tmp: /tmp/.ansible/tmp