---
# Connection settings
ansible_connection: community.aws.aws_ssm
ansible_aws_ssm_region: us-east-1
# ansible_aws_ssm_bucket_name: devops-ansible-transfer-686255953032  
# Optional - only needed for large file transfers
# utilize default ssm bucket ansible-ssm-transfer-<account-id>-region
ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3

# Temp directories
remote_tmp: /tmp/.ansible/tmp
local_tmp: /tmp/.ansible/tmp